// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using MoonquakeExplorer.Data;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace MoonquakeExplorer.Data.Migrations
{
    [DbContext(typeof(MoonquakeDbContext))]
    [Migration("20260929151035_AddUniqueOccurredAtIndex")]
    partial class AddUniqueOccurredAtIndex
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("MoonquakeExplorer.Data.Models.MoonquakeRecord", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<double?>("AmplitudeApollo11_12")
                        .HasColumnType("double precision");

                    b.Property<double?>("AmplitudeApollo14")
                        .HasColumnType("double precision");

                    b.Property<double?>("AmplitudeApollo15")
                        .HasColumnType("double precision");

                    b.Property<double?>("AmplitudeApollo16")
                        .HasColumnType("double precision");

                    b.Property<int?>("Apollo12Lpx")
                        .HasColumnType("integer");

                    b.Property<int?>("Apollo12Lpy")
                        .HasColumnType("integer");

                    b.Property<int?>("Apollo12Lpz")
                        .HasColumnType("integer");

                    b.Property<int?>("Apollo14Lpx")
                        .HasColumnType("integer");

                    b.Property<int?>("Apollo14Lpy")
                        .HasColumnType("integer");

                    b.Property<int?>("Apollo14Lpz")
                        .HasColumnType("integer");

                    b.Property<int?>("Apollo14Spz")
                        .HasColumnType("integer");

                    b.Property<int?>("Apollo15Lpx")
                        .HasColumnType("integer");

                    b.Property<int?>("Apollo15Lpy")
                        .HasColumnType("integer");

                    b.Property<int?>("Apollo15Lpz")
                        .HasColumnType("integer");

                    b.Property<int?>("Apollo15Spz")
                        .HasColumnType("integer");

                    b.Property<int?>("Apollo16Lpx")
                        .HasColumnType("integer");

                    b.Property<int?>("Apollo16Lpy")
                        .HasColumnType("integer");

                    b.Property<int?>("Apollo16Lpz")
                        .HasColumnType("integer");

                    b.Property<int?>("Apollo16Spz")
                        .HasColumnType("integer");

                    b.Property<int?>("ClusterNumber")
                        .HasColumnType("integer");

                    b.Property<string>("Comments")
                        .HasColumnType("text");

                    b.Property<int?>("DataQualityApollo11_12")
                        .HasColumnType("integer");

                    b.Property<int?>("DataQualityApollo14")
                        .HasColumnType("integer");

                    b.Property<int?>("DataQualityApollo15")
                        .HasColumnType("integer");

                    b.Property<int?>("DataQualityApollo16")
                        .HasColumnType("integer");

                    b.Property<string>("EventType")
                        .HasColumnType("text");

                    b.Property<string>("Grade")
                        .HasColumnType("text");

                    b.Property<int?>("JulianDay")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("OccurredAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("OriginalClusterNumber")
                        .HasColumnType("integer");

                    b.Property<string>("OriginalEventType")
                        .HasColumnType("text");

                    b.Property<int?>("PlotAvailabilityApollo11_12")
                        .HasColumnType("integer");

                    b.Property<int?>("PlotAvailabilityApollo14")
                        .HasColumnType("integer");

                    b.Property<int?>("PlotAvailabilityApollo15")
                        .HasColumnType("integer");

                    b.Property<int?>("PlotAvailabilityApollo16")
                        .HasColumnType("integer");

                    b.Property<int?>("SignalStartTime")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("SignalStartedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("SignalStopTime")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("SignalStoppedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("Traces")
                        .HasColumnType("integer");

                    b.Property<int?>("Year")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("OccurredAt")
                        .IsUnique();

                    b.ToTable("Moonquakes", (string)null);
                });

            modelBuilder.Entity("MoonquakeExplorer.Data.Models.SeismicStationRecord", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<double>("Latitude")
                        .HasColumnType("double precision");

                    b.Property<double>("Longitude")
                        .HasColumnType("double precision");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("Id");

                    b.ToTable("SeismicStations", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("11111111-1111-1111-1111-111111111111"),
                            IsActive = true,
                            Latitude = -3.0097999999999998,
                            Longitude = -23.424900000000001,
                            Name = "Apollo 12"
                        },
                        new
                        {
                            Id = new Guid("22222222-2222-2222-2222-222222222222"),
                            IsActive = true,
                            Latitude = -3.64419,
                            Longitude = -17.477679999999999,
                            Name = "Apollo 14"
                        },
                        new
                        {
                            Id = new Guid("33333333-3333-3333-3333-333333333333"),
                            IsActive = true,
                            Latitude = 26.134060000000002,
                            Longitude = 3.6299100000000002,
                            Name = "Apollo 15"
                        },
                        new
                        {
                            Id = new Guid("44444444-4444-4444-4444-444444444444"),
                            IsActive = true,
                            Latitude = -8.9758999999999993,
                            Longitude = 15.4986,
                            Name = "Apollo 16"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
