// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using MoonquakeExplorer.Data;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace MoonquakeExplorer.Data.Migrations
{
    [DbContext(typeof(MoonquakeDbContext))]
    [Migration("20260928204255_AddFullMoonquakeData")]
    partial class AddFullMoonquakeData
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("MoonquakeExplorer.Data.Models.MoonquakeRecord", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<double?>("AmplitudeApollo11_12")
                        .HasColumnType("double precision");

                    b.Property<double?>("AmplitudeApollo14")
                        .HasColumnType("double precision");

                    b.Property<double?>("AmplitudeApollo15")
                        .HasColumnType("double precision");

                    b.Property<double?>("AmplitudeApollo16")
                        .HasColumnType("double precision");

                    b.Property<int?>("Apollo12Lpx")
                        .HasColumnType("integer");

                    b.Property<int?>("Apollo12Lpy")
                        .HasColumnType("integer");

                    b.Property<int?>("Apollo12Lpz")
                        .HasColumnType("integer");

                    b.Property<int?>("Apollo14Lpx")
                        .HasColumnType("integer");

                    b.Property<int?>("Apollo14Lpy")
                        .HasColumnType("integer");

                    b.Property<int?>("Apollo14Lpz")
                        .HasColumnType("integer");

                    b.Property<int?>("Apollo14Spz")
                        .HasColumnType("integer");

                    b.Property<int?>("Apollo15Lpx")
                        .HasColumnType("integer");

                    b.Property<int?>("Apollo15Lpy")
                        .HasColumnType("integer");

                    b.Property<int?>("Apollo15Lpz")
                        .HasColumnType("integer");

                    b.Property<int?>("Apollo15Spz")
                        .HasColumnType("integer");

                    b.Property<int?>("Apollo16Lpx")
                        .HasColumnType("integer");

                    b.Property<int?>("Apollo16Lpy")
                        .HasColumnType("integer");

                    b.Property<int?>("Apollo16Lpz")
                        .HasColumnType("integer");

                    b.Property<int?>("Apollo16Spz")
                        .HasColumnType("integer");

                    b.Property<int?>("ClusterNumber")
                        .HasColumnType("integer");

                    b.Property<string>("Comments")
                        .HasColumnType("text");

                    b.Property<int?>("DataQualityApollo11_12")
                        .HasColumnType("integer");

                    b.Property<int?>("DataQualityApollo14")
                        .HasColumnType("integer");

                    b.Property<int?>("DataQualityApollo15")
                        .HasColumnType("integer");

                    b.Property<int?>("DataQualityApollo16")
                        .HasColumnType("integer");

                    b.Property<string>("EventType")
                        .HasColumnType("text");

                    b.Property<string>("Grade")
                        .HasColumnType("text");

                    b.Property<int?>("JulianDay")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("OccurredAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("OriginalClusterNumber")
                        .HasColumnType("integer");

                    b.Property<string>("OriginalEventType")
                        .HasColumnType("text");

                    b.Property<int?>("PlotAvailabilityApollo11_12")
                        .HasColumnType("integer");

                    b.Property<int?>("PlotAvailabilityApollo14")
                        .HasColumnType("integer");

                    b.Property<int?>("PlotAvailabilityApollo15")
                        .HasColumnType("integer");

                    b.Property<int?>("PlotAvailabilityApollo16")
                        .HasColumnType("integer");

                    b.Property<Guid>("RecordingStationId")
                        .HasColumnType("uuid");

                    b.Property<int?>("SignalStartTime")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("SignalStartedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("SignalStopTime")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("SignalStoppedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("Traces")
                        .HasColumnType("integer");

                    b.Property<int?>("Year")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("RecordingStationId");

                    b.ToTable("Moonquakes", (string)null);
                });

            modelBuilder.Entity("MoonquakeExplorer.Data.Models.SeismicStationRecord", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<double>("Latitude")
                        .HasColumnType("double precision");

                    b.Property<double>("Longitude")
                        .HasColumnType("double precision");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("Id");

                    b.ToTable("SeismicStations", (string)null);
                });

            modelBuilder.Entity("MoonquakeExplorer.Data.Models.MoonquakeRecord", b =>
                {
                    b.HasOne("MoonquakeExplorer.Data.Models.SeismicStationRecord", "RecordingStation")
                        .WithMany()
                        .HasForeignKey("RecordingStationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("RecordingStation");
                });
#pragma warning restore 612, 618
        }
    }
}
